name: Build JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      #- uses: actions/setup-node@v6
      #  with:
      #    node-version: "latest"
      #    cache: npm

      - name: Setup npm
        run: |
          npm init -y
          npm install -D typescript tsx
      
      - name: Run Script
        run: npx tsx src/build_json.ts

      - name: Publish JSON
        run: |
          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot <support+actions@github.com>"


          # Save generated file
          cp output.json /tmp/output.json

          # Branches
          git fetch origin output-json

          # Create worktree folder named "publish"
          git worktree add publish output-json

          # Copy file into worktree folder.
          cp output.json publish/output.json

          # Enter worktree
          cd publish
          
          git add output.json
          git commit -m "Generated JSON"
          git push origin output-json --force


          # Done
          cd ..
          git worktree remove publish
